apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-container 
          image: 69966/springgradleimg:1.1.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: my-vol
              mountPath: /app/src/main/resources/images
      volumes:
        - name: my-vol 
          nfs:
            server: 10.184.0.4
            path: /opt/nfs/data
---
apiVersion: v1
kind: Service 
metadata:
  name: spring-svc
spec:
  type: ClusterIP
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080
---
# create ingress for the spring application 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingresClassName: nginx
spec:
  tls:
    - hosts:
        - ag.kuberthy.me
      secretName: myspring-tls 
  rules:
    - host: ag.kuberthy.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-svc
                port:
                  number: 8080